# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 924e90586757883cfe7e5150b75c38e11d7f8282b778edbd6ff0a3b2873628a6d96c5d0029a39da2329dec880c97b3a9c20d5a9e61eb8dbe5d4cbaf070632006

test:
  secret_key_base: 919056319605f3b64e57228c5f31ab7e7fb27430cdf41755033005ee6841f0f9278a1bed75eff9b6635a6e94cdff25cc759ed974d9c39ce3d90727a2985a701d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
